package
{
	public class HeroImg
	{
		public function HeroImg()
		{
			// 缺省
		}
		public function GetID(Name:String):int
		{		
            switch (Name)
            {
                case "佐天泪子": 
                    return 2;
                case "御坂美琴": 
                    return 3;
                case "白井黑子": 
                    return 4;
                case "初春饰利": 
                    return 5;
                case "固法美伟": 
                    return 6;
                case "婚后光子": 
                    return 7;
                case "湾内绢保": 
                    return 8;
                case "泡浮万彬": 
                    return 9;
                case "上条当麻": 
                    return 10;
                case "御坂妹妹": 
                    return 11;
                case "史提尔": 
                    return 12;
				case "最后之作":
					return 13;
				case "食蜂操祈":
					return 14;
				case "鸣护艾丽莎":
					return 15;
				case "一方通行":
					return 16;
				case "黄泉川爱穗":
					return 17;
				case "土御门元春":
					return 18;
				case "冥土追魂":
					return 19;

                case "博丽灵梦": 
                    return 31;
				case "雾雨魔理沙":
                case "魔理沙": 
                    return 32;
                case "爱丽丝": 
                    return 33;
                case "帕秋莉": 
                    return 34;
                case "十六夜咲夜": 
                    return 35;
                case "红美铃": 
                    return 36;
                case "东风谷早苗": 
                    return 37;
                case "藤原妹红": 
                    return 38;
                case "铃仙": 
                    return 39;
                case "魂魄妖梦": 
                    return 40;
				case "射命丸文":
					return 41;
				case "幽幽子":
				case "西行寺幽幽子":
					return 42;
				case "米斯蒂娅":
				case "夜雀":
				case "老板娘":
					return 43;
				case "姬海棠极":
					return 44;
				case "琪露诺":
					return 45;
				case "八云紫":
					return 46;
				case "天子":
				case "比那名居天子":
					return 47;

                case "柯南": 
                    return 61;
                case "灰原哀": 
                    return 62;
                case "乌贼娘": 
                    return 63;
                case "和美": 
                    return 64;
                case "小鸟游六花": 
                    return 65;
                case "七宫智音": 
                    return 66;
                case "富檻勇太": 
                    return 67;
                case "晓美焰": 
                    return 68;
                case "鹿目圆": 
                    return 69;
                case "阿虚": 
                    return 70;
                case "古泉一树": 
                    return 71;
                case "我妻由乃": 
                    return 72;
                case "毛利小五郎": 
                    return 73;
                case "栗山未来": 
                    return 74;
                case "朝比奈实玖瑠": 
                    return 75;
                case "长门有希": 
                    return 76;
                case "凉宫春日": 
                    return 77;

                case "忠邦": 
                    return 81;
                case "秀则": 
                    return 82;
                case "吉竹": 
                    return 83;
                case "折木奉太郎": 
                    return 84;
                case "千反田爱瑠": 
                    return 85;
                case "黑雪姬": 
                    return 86;
				case "奈亚子":
					return 87;
				case "克子":
					return 88;
				case "哈斯塔":
					return 89;
				case "八坂真寻":
					return 90;
				case "亚丝娜":
				case "结城明日奈":
					return 91;
				case "桐人":
				case "桐谷和人":
					return 92;
				case "五河士道":
					return 93;
				case "胖虎":
					return 94;
				case "目暮十三":
					return 95;
				case "久川铁道":
				case "波波":
					return 96;
				case "巴麻美":
					return 97;
				case "时崎狂三":
					return 98;
				case "鸢一折纸":
					return 99;
				case "崇宫真那":
					return 100;
            }
			return 1;
		}
		public function GetPosition(Name:String):int
		{	
            switch (Name)
            {
                case "佐天泪子": 
                    return 3;
                case "御坂美琴": 
                    return 3;
                case "白井黑子": 
                    return 2;
                case "初春饰利": 
                    return 1;
                case "固法美伟": 
                    return 1;
                case "婚后光子": 
                    return 1;
                case "湾内绢保": 
                    return 2;
                case "泡浮万彬": 
                    return 3;
                case "上条当麻": 
                    return 2;
                case "御坂妹妹": 
                    return 2;
                case "史提尔": 
                    return 2;
				case "最后之作":
					return 1;
				case "食蜂操祈":
					return 1;
				case "鸣护艾丽莎":
					return 2;
				case "一方通行":
					return 2;
				case "黄泉川爱穗":
					return 2;
				case "土御门元春":
					return 2;
				case "冥土追魂":
					return 2;

                case "博丽灵梦": 
                    return 1;
                case "魔理沙": 
                    return 3;
                case "爱丽丝": 
                    return 1;
                case "帕秋莉": 
                    return 2;
                case "十六夜咲夜": 
                    return 2;
                case "红美铃": 
                    return 2;
                case "东风谷早苗": 
                    return 2;
                case "藤原妹红": 
                    return 3;
                case "铃仙": 
                    return 1;
                case "魂魄妖梦": 
                    return 3;
				case "射命丸文":
					return 2;
				case "幽幽子":
				case "西行寺幽幽子":
					return 1;
				case "米斯蒂娅":
				case "夜雀":
				case "老板娘":
					return 3;
				case "姬海棠极":
					return 2;
				case "琪露诺":
					return 1;
				case "八云紫":
					return 2;
				case "天子":
				case "比那名居天子":
					return 2;

                case "柯南": 
                    return 3;
                case "灰原哀": 
                    return 1;
                case "乌贼娘": 
                    return 2;
                case "和美": 
                    return 3;
                case "小鸟游六花": 
                    return 1;
                case "七宫智音": 
                    return 2;
                case "富檻勇太": 
                    return 1;
                case "晓美焰": 
                    return 2;
                case "鹿目圆": 
                    return 2;
                case "阿虚": 
                    return 3;
                case "古泉一树": 
                    return 2;
                case "我妻由乃": 
                    return 2;
                case "毛利小五郎": 
                    return 1;
                case "栗山未来": 
                    return 2;
                case "朝比奈实玖瑠": 
                    return 2;
                case "长门有希": 
                    return 3;
                case "凉宫春日": 
                    return 2;

                case "忠邦": 
                    return 3;
                case "秀则": 
                    return 1;
                case "吉竹": 
                    return 2;
                case "折木奉太郎": 
                    return 1;
                case "千反田爱瑠": 
                    return 2;
                case "黑雪姬": 
                    return 3;
				case "奈亚子":
					return 3;
				case "克子":
					return 2;
				case "哈斯塔":
					return 3;
				case "八坂真寻":
					return 3;
				case "亚丝娜":
				case "结城明日奈":
					return 2;
				case "桐人":
				case "桐谷和人":
					return 1;
				case "五河士道":
					return 1;
				case "胖虎":
					return 1;
				case "目暮十三":
					return 2;
				case "久川铁道":
				case "波波":
					return 2;
				case "巴麻美":
					return 1;
				case "时崎狂三":
					return 2;
				case "鸢一折纸":
					return 2;
				case "崇宫真那":
					return 2;
            }
			return 2;
		}
	}
}